name: Build and Publish GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0 or latest)'
        required: false
        default: 'latest'

jobs:
  build-and-publish-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        mode:
          - name: default
            simple_mode: false
            suffix: ''
          - name: simple
            simple_mode: true
            suffix: '-simple'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}${{ matrix.mode.suffix }}
          tags: |
            type=raw,value=${{ github.event.inputs.version || 'latest' }}
            type=raw,value=latest,enable=${{ github.event.inputs.version == '' || github.event.inputs.version == 'latest' }}

      - name: Build and push ${{ matrix.mode.name }} package
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            SIMPLE_MODE=${{ matrix.mode.simple_mode }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
